clear;
figure;
N=512;
n=64;
t=1:2*n+1;
x=zeros(2*n+1); 
x=transpose(cos(2*pi*t/n))*sin(2*pi*0.5*t/n + pi/sqrt(2)); 
y=zeros(N); 
y(N/2+(-n:n),N/2+(-n:n)) = 1+x; 
subplot(2,2,1); 
imagesc(y); colormap('gray');
title('original function in x'); 
subplot(2,2,2); 
w=fft2(y); 
w = w([N/2:N,1:N/2-1],:); 
w=w(:,[N/2:N,1:N/2-1]); 
wcrop = w(N/2+(-2*n:2*n),N/2+(-2*n:2*n)); 
imagesc(abs(wcrop)); colormap('gray');
title('abs(fft)'); 
subplot(2,2,3); 
imagesc(atan2(imag(wcrop),real(wcrop)),[-pi,pi]); colormap('gray');
title('phase(fft)'); 
%colormap('hsv');

figure;
x=-15:0.001:15;
y=exp(-x.^2).*(1 + 0.250*sin(4*2*pi*x) + 1*(x>-0.75 & x<0.5));
subplot(3,1,1);
plot(x,y);
title('original function');
w=fft(y);k=1:length(w);
k=k([floor(length(w)/2):length(w) , 1:floor(length(w)/2)-1]);
subplot(3,1,2);plot(k,abs(w));
xlim(mean(k)+128*[-1,1]); title('abs(fft)');
subplot(3,1,3);
plot(k,atan2(imag(w),real(w)),'.');
xlim(mean(k)+128*[-1,1]);
title('phase');